services:

  https-portal:
    environment:
      DOMAINS: >
        mailpit.safe-exam.test -> http://mailpit:8025,
        ${HTTPS_PORTAL_SITES}
    depends_on:
      - mailpit

  php:
    image: plantilla-laravel-php-dev
    build:
      dockerfile: Dockerfile.php.dev

  phpmyadmin:
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}

  mailpit:
    image: axllent/mailpit:${MAILPIT_VERSION:-latest}
